version: '3'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  pishkot:
    container_name: pishkot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SLACK_TOKEN: ${SLACK_TOKEN}
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres